### ISSUE TITLE
Cache short survey URL in DB

### ISSUE THREAD

**Issue by lukasbischof** [orsa-scholis/evaweb#67]
Currently, each time you open the dashboard, a request is sent to bit.ly even though we actually would already know the short link. I also don't know how shortening the same URL affects out API usage limit, maybe this would also draw from it.

**Comment by lukasbischof** [comment]
@TheFehr What you think?

**Comment by TheFehr** [comment]
Sounds reasonable. But can we verify the API usage limit is actually used up?

**Comment by lukasbischof** [comment]
Idk, maybe not as it‘s intelligent enough to recognize that is same link. But anyway we‘re sending synchronous request which is not best for performance

**Comment by TheFehr** [comment]
Yeah but the same dashboard won't be openend many times. Normaly only once.

**Comment by lukasbischof** [comment]
Yes, normally, in our workflow. But you never know what users will actually do 😉
